# Generated by Django 2.1.2 on 2018-11-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Loko',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=30, verbose_name='Серия')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ставка')),
            ],
            options={
                'ordering': ('rate',),
            },
        ),
        migrations.AddField(
            model_name='filial',
            name='Loko',
            field=models.ManyToManyField(blank=True, to='page.Loko'),
        ),
    ]
