# Generated by Django 2.1.2 on 2018-11-01 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filial',
            old_name='Loko',
            new_name='lokos',
        ),
    ]
