# Generated by Django 2.1.2 on 2018-11-01 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20181101_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mileage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(choices=[('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024')], max_length=10, verbose_name='Год пробега')),
                ('mileage', models.IntegerField(verbose_name='Пробег в км')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Filial', verbose_name='Филиал')),
            ],
        ),
        migrations.AlterField(
            model_name='loko',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ставка за км'),
        ),
        migrations.AlterField(
            model_name='loko',
            name='series',
            field=models.CharField(max_length=30, verbose_name='Серия локомотива'),
        ),
        migrations.AddField(
            model_name='mileage',
            name='loko',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Loko', verbose_name='Серия локомотива'),
        ),
    ]
