# Generated by Django 2.1.2 on 2018-11-01 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20181101_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filial',
            options={'ordering': ('name',), 'verbose_name': 'Филиал', 'verbose_name_plural': 'Филиалы'},
        ),
        migrations.AlterModelOptions(
            name='loko',
            options={'ordering': ('series',), 'verbose_name': 'Локомотив', 'verbose_name_plural': 'Локомотивы'},
        ),
        migrations.AlterModelOptions(
            name='mileage',
            options={'ordering': ('year',), 'verbose_name': 'Пробег', 'verbose_name_plural': 'Пробеги'},
        ),
        migrations.RenameField(
            model_name='mileage',
            old_name='choices',
            new_name='year',
        ),
    ]
