# Generated by Django 2.1.2 on 2018-11-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20181101_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='slug',
            field=models.SlugField(blank=True, default='page-slug', max_length=100),
        ),
        migrations.AddField(
            model_name='loko',
            name='slug',
            field=models.SlugField(blank=True, default='page-slug', max_length=30),
        ),
    ]
