# Generated by Django 2.1.2 on 2018-11-02 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_auto_20181102_0852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loko',
            options={'ordering': ('name',), 'verbose_name': 'Локомотив', 'verbose_name_plural': 'Локомотивы'},
        ),
        migrations.RenameField(
            model_name='loko',
            old_name='series',
            new_name='name',
        ),
    ]
