# Generated by Django 2.1.2 on 2018-11-02 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_auto_20181102_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filial',
            name='lokos',
        ),
    ]
