# Generated by Django 2.1.2 on 2018-11-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_remove_filial_lokos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loko',
            options={'ordering': ('id',), 'verbose_name': 'Локомотив', 'verbose_name_plural': 'Локомотивы составками за км'},
        ),
        migrations.AlterField(
            model_name='mileage',
            name='year',
            field=models.CharField(choices=[('2017', 2017), ('2018', 2018), ('2019', 2019), ('2020', 2020), ('2021', 2021), ('2022', 2022), ('2023', 2023), ('2024', 2024)], max_length=10, verbose_name='Год пробега'),
        ),
    ]
